# Generated by Django 2.2.10 on 2020-07-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Columns",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="column name")),
                ("width", models.PositiveIntegerField(verbose_name="column width")),
                (
                    "order_number",
                    models.PositiveIntegerField(verbose_name="Order number"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FilePath",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=400)),
            ],
        ),
    ]
